version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "9091:8000"

  firestore:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=dummy-project-id
      - PORT=8200
    ports:
      - "8200:8200"
